/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'Main': {
        'en': 'main site',
        'de': 'Hauptseite',
        'ru': 'главный сайт',
        'pt': 'site principal',
        'nl': 'hoofdsite',
        'fr': 'site principal',
        'it': 'sito principale',
        'es': 'sitio principal',
        'pl': 'strona główna',
        'zh-cn': '主要地点'
    },
    'Google': {
        'en': 'Google',
        'de': 'Google',
        'ru': 'Google',
        'pt': 'Google',
        'nl': 'Google',
        'fr': 'Google',
        'it': 'Google',
        'es': 'Google',
        'pl': 'Google',
        'zh-cn': '谷歌'
    },
    'CalDav': {
        'en': 'CalDav',
        'de': 'CalDav',
        'ru': 'CalDav',
        'pt': 'CalDav',
        'nl': 'CalDav',
        'fr': 'CalDav',
        'it': 'CalDav',
        'es': 'CalDav',
        'pl': 'CalDav',
        'zh-cn': '卡尔达夫'
    },
    'FQDN:': {
        'en': 'FQDN:',
        'de': 'FQDN:',
        'ru': 'Полное доменное имя:',
        'pt': 'FQDN:',
        'nl': 'FQDN:',
        'fr': 'FQDN:',
        'it': 'FQDN:',
        'es': 'FQDN:',
        'pl': 'FQDN:',
        'zh-cn': 'FQDN:'
    },
    'Port:': {
        'en': 'Port:',
        'de': 'Port:',
        'ru': 'Порт:',
        'pt': 'Porta:',
        'nl': 'Haven:',
        'fr': 'Port:',
        'it': 'Porta:',
        'es': 'Puerto:',
        'pl': 'Port:',
        'zh-cn': '港口：'
    },
    'Activate Google': {
        'en': 'Activate Google',
        'de': 'Google aktivieren',
        'ru': 'Активировать гугл',
        'pt': 'Ativar Google',
        'nl': 'Activeer Google',
        'fr': 'Activer Google',
        'it': 'Attiva Google',
        'es': 'Activa Google',
        'pl': 'Aktywuj Google',
        'zh-cn': '激活谷歌'
    },
    'Client ID:': {
        'en': 'Client ID:',
        'de': 'Client ID:',
        'ru': 'ID клиента:',
        'pt': 'ID do Cliente:',
        'nl': 'Klant identificatie:',
        'fr': 'Identité du client:',
        'it': 'Identificativo cliente:',
        'es': 'Identificación del cliente:',
        'pl': 'Identyfikator klienta:',
        'zh-cn': '客户编号：'
    },
    'Client Secret:': {
        'en': 'Client Secret:',
        'de': 'Client Secret:',
        'ru': 'Секрет клиента:',
        'pt': 'Segredo do cliente:',
        'nl': 'Klantgeheim:',
        'fr': 'Secret client:',
        'it': 'Segreto cliente:',
        'es': 'Secreto del cliente:',
        'pl': 'Sekret klienta:',
        'zh-cn': '客户机密：'
    },
    'active': {
        'en': 'active',
        'de': 'aktiv',
        'ru': 'активный',
        'pt': 'ativo',
        'nl': 'actief',
        'fr': 'actif',
        'it': 'attivo',
        'es': 'activo',
        'pl': 'aktywny',
        'zh-cn': '活性'
    },
    'name': {
        'en': 'name',
        'de': 'Name',
        'ru': 'имя',
        'pt': 'nome',
        'nl': 'naam',
        'fr': 'Nom',
        'it': 'nome',
        'es': 'nombre',
        'pl': 'Nazwa',
        'zh-cn': '名称'
    },
    'days': {
        'en': 'days',
        'de': 'Tage',
        'ru': 'дней',
        'pt': 'dias',
        'nl': 'dagen',
        'fr': 'journées',
        'it': 'giorni',
        'es': 'dias',
        'pl': 'dni',
        'zh-cn': '天'
    },
    'color': {
        'en': 'color',
        'de': 'Farbe',
        'ru': 'цвет',
        'pt': 'cor',
        'nl': 'kleur',
        'fr': 'Couleur',
        'it': 'colore',
        'es': 'color',
        'pl': 'kolor',
        'zh-cn': '颜色'
    },
    'Activate CalDAV': {
        'en': 'Activate CalDAV',
        'de': 'CalDAV aktivieren',
        'ru': 'Активировать CalDAV',
        'pt': 'Ativar CalDAV',
        'nl': 'Activeer CalDAV',
        'fr': 'Activez CalDAV',
        'it': 'Attiva CalDAV',
        'es': 'Activa CalDAV',
        'pl': 'Aktywuj CalDAV',
        'zh-cn': '激活CalDAV'
    },
    'hostname': {
        'en': 'hostname',
        'de': 'Hostname',
        'ru': 'имя хоста',
        'pt': 'nome de anfitrião',
        'nl': 'hostname',
        'fr': "nom d'hôte",
        'it': 'Nome host',
        'es': 'nombre de host',
        'pl': 'nazwa hosta',
        'zh-cn': '主机名'
    },
    'username': {
        'en': 'username',
        'de': 'Nutzername',
        'ru': 'имя пользователя',
        'pt': 'nome do usuário',
        'nl': 'gebruikersnaam',
        'fr': "Nom d'utilisateur",
        'it': 'nome utente',
        'es': 'nombre de usuario',
        'pl': 'Nazwa Użytkownika',
        'zh-cn': '用户名'
    },
    'password': {
        'en': 'password',
        'de': 'Passwort',
        'ru': 'пароль',
        'pt': 'senha',
        'nl': 'wachtwoord',
        'fr': 'mot de passe',
        'it': "parola d'ordine",
        'es': 'contraseña',
        'pl': 'hasło',
        'zh-cn': '密码'
    }
};